server:
  port: 8085



spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
  datasource:
    url: jdbc:postgresql://localhost:5432/mysimplebot
    username: userok
    password: p@ssw0rd
  jpa:
    generate-ddl: true